### ISSUE TITLE
selected option is not getting assigned to ng-model variable

### ISSUE THREAD

**Issue by brickcube-shweta** [Attrash-Islam/ng-infinite-autocomplete#28]

**Comment by Attrash-Islam** [comment]
I was in a vecation. I'll check it as soon as possible

**Comment by Attrash-Islam** [comment]
I'll add this in the next release in the next two days :+1: Thanks for reporting :heart:  and Sorry for being late

**Comment by Attrash-Islam** [comment]
Upgrade to + ng-infinite-autocomplete@3.2.0 to get this feature. Thanks for reporting again and sorry for the delay
